---
include:
  - project: nci-gdc/gitlab-templates
    ref: master
    file:
      - templates/artifacts/python-docker-service.yaml

.services:
  allow_failure: true
  when: manual
  parallel:
    matrix:
      - DEPLOY_SERVICE_LIST: [esbuild]

variables:
  BASE_CONTAINER_VERSION: 3.1.0
  LANGUAGE_VERSION: python3.9

tox:
  services:
    - name: docker.osdc.io/ncigdc/ci-postgres-13:${BASE_CONTAINER_VERSION}
      alias: postgres
    - name: docker.osdc.io/ncigdc/ci-elasticsearch-7:${BASE_CONTAINER_VERSION}
      alias: elasticsearch
  variables:
    # these are for postgres docker
    POSTGRES_DB: automated_test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: test
    POSTGRES_HOST_AUTH_METHOD: trust
    # these are for tox
    PG_ESBUILD_HOST: postgres
    PG_INDEXD_HOST: postgres
    ES_HOST: elasticsearch
