---

include:
  - project: nci-gdc/gitlab-templates
    ref: 0.3.1
    file:
      - templates/global/full.yaml
      - templates/python/full.yaml
      - templates/common/python.yaml
      - templates/common/docker.yaml
      - templates/deployments/salt-service.yaml

.services:
  allow_failure: true
  stage: deploy
  when: manual
  parallel:
    matrix:
      - DEPLOY_SERVICE_LIST: [esbuild]

tox:
  parallel:
    matrix:
      - BUILD_PY_VERSION: [python3.9]
  services:
    - name: docker.osdc.io/ncigdc/ci-postgres-13:${BASE_CONTAINER_VERSION}
      alias: postgres
    - name: docker.osdc.io/ncigdc/ci-elasticsearch-7:${BASE_CONTAINER_VERSION}
      alias: elasticsearch
  variables:
    # these are for postgres docker
    POSTGRES_DB: automated_test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: test
    POSTGRES_HOST_AUTH_METHOD: trust
    # these are for tox
    PG_ESBUILD_HOST: postgres
    PG_INDEXD_HOST: postgres
    ES_HOST: elasticsearch
  script:
    - pip install "tox<4"
    - tox -r -e py


release:
  variables:
    RELEASE_PY_VERSION: python3.9
  before_script:
    - git fetch --unshallow || true
  after_script:
    - python setup.py --version > VERSION.txt
  artifacts:
    paths:
      - VERSION.txt
    expire_in: 1 week
