---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
        exclude: ^helm/templates/
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [--branch, develop, --branch, master, --pattern, release/.*]
      - id: pretty-format-json
        args: [--autofix]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.1          # use 1.7.1 for python3.6
    hooks:
      - id: bandit
        args: [--skip, 'B303,B101,B404,B405,B607,B603', --exclude, tests]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: git@github.com:Yelp/detect-secrets
    rev: v1.1.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.5.4
    hooks:
      - id: isort
        args: [--profile, black]
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.1.0
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2', --width, '80']
        exclude: ^helm/templates/
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.18.0
    hooks:
      - id: toml-sort
        args: [--in-place]
