---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
        exclude: ^\.gitlab-ci.yml
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: [--remove]
      - id: no-commit-to-branch
        args: [--branch, develop, --branch, master, --pattern, release/.*]
      - id: pretty-format-json
        args: [--autofix]
      - id: trailing-whitespace
        exclude: ^\.travis.yml
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.15
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
        exclude: .(py|yaml|yml|tsv)$
      - id: remove-tabs
        exclude: .(py|yaml|yml|tsv)$
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.1          # use 1.7.1 for python3.6
    hooks:
      - id: bandit
        args: [--skip, 'B303,B101,B404,B405,B607,B603', --exclude, tests]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: [--profile, black]
      - id: isort
        name: isort (cython)
        types: [cython]
        args: [--profile, black]
      - id: isort
        name: isort (pyi)
        types: [pyi]
        args: [--profile, black]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        args: [convention=google, --add-ignore, 'D100,D101,D102,D103,D104,D105,D106,D107']
        exclude: ^(tests|unit_tests)/
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.1
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2', --width, '80']
        exclude: ^helm/templates/
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.18.0
    hooks:
      - id: toml-sort
        args: [--in-place]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]
