language: python
dist: bionic

python:
  - "3.6"

sudo: true

env:
  - ES_HOST='localhost' ES_VERSION="7.6.2"

addons:
  postgresql: "13"
  apt:
    sources:
      - sourceline: deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main 13
        key_url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    packages:
      - postgresql-13
      - postgresql-client-13

before_install:
  # Copy custom configs from the repo because PG-13 isn't set up to run like
  # it normally does on Travis out of the box.
  - sudo cp travis/postgresql.conf /etc/postgresql/13/main/postgresql.conf
  - sudo cp travis/pg_hba.conf /etc/postgresql/13/main/pg_hba.conf
  - sudo pg_ctlcluster 13 main restart

install:
  # Install and start elasticsearch
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}-amd64.deb && sudo dpkg --force-confnew -i elasticsearch-${ES_VERSION}-amd64.deb
  - sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install mapper-size
  - sudo sed -i 's/^-Xms.*/-Xms2g/' /etc/elasticsearch/jvm.options
  - sudo sed -i 's/^-Xmx.*/-Xmx2g/' /etc/elasticsearch/jvm.options
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo service elasticsearch start

  # Make sure we have a new enough virtualenv to get a version of pip that
  # understands VCS URLs. Install virtualenv before running tox because
  # tox-travis seems to break if we let tox upgrade it for us.
  - pip install tox-travis 'virtualenv>=20.0.21' 'pip >= 20.1.1'

before_script:
  # Wait for elasticsearch to be up
  - printf 'Waiting for Elasticsearch '; until curl localhost:9200 2> /dev/null; do printf '.'; sleep 1; done; printf ' done'
  - psql -U postgres -c "create user test with superuser password 'test'"
  - psql -U postgres -c "create database automated_test with owner test"
  - psql -U postgres -c "create user ro_test with password 'ro_test'"

script: "tox"

after_script:
  - curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
  - artifacts --quiet upload --bucket gdc-travis-artifacts --target-paths "$TRAVIS_REPO_SLUG/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER/" tests/htmlcov/
  - "echo Artifact link: https://gdc-travis-artifacts.osdc.io/${TRAVIS_REPO_SLUG}/${TRAVIS_BUILD_NUMBER}/${TRAVIS_JOB_NUMBER}"
