language: generic

node: 6

sudo: true

env:
  - ES_HOST='localhost' ES_VERSION=5.6.14 NODE_VERSION=10 BOTO_CONFIG=/dev/null

addons:
  postgresql: '9.4'

before_install:
  # Upgrade npm
  - npm install -g npm@'>=6'
  - unset PYENV_ROOT
  - rm -rf ~/.pyenv
  - curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
  - export PATH="$HOME/.pyenv/bin:$PATH"
  - pyenv install 3.5.7
  - pyenv install 3.6.9


install:
  # Update nodejs
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm 
  - (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)
  - source ~/.nvm/nvm.sh && nvm install $NODE_VERSION

  # Install and start elasticsearch
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.deb
  - sudo dpkg -i --force-confnew elasticsearch-${ES_VERSION}.deb
  - sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install mapper-size
  - sudo service elasticsearch start
  
  # Install elasticdump and other requirements
  - npm install -g elasticdump
  - virtualenv venv
  - source venv/bin/activate
  - pip install tox-travis tox-pyenv

before_script:
  - pip freeze
  # Wait for elasticsearch to be up
  - printf 'Waiting for Elasticsearch '; until curl localhost:9200 2> /dev/null; do printf '.'; sleep 1; done; printf ' done'
  - psql -U postgres -c "create user test with superuser password 'test'"
  - psql -U postgres -c "create database automated_test with owner test"

script:
  - pyenv local 3.5.7 3.6.9
  - tox -e py35,py36

after_script:
  - curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
  - artifacts --quiet upload --bucket gdc-travis-artifacts --target-paths "$TRAVIS_REPO_SLUG/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER/" htmlcov/
  - "echo Artifact link: https://gdc-travis-artifacts.osdc.io/${TRAVIS_REPO_SLUG}/${TRAVIS_BUILD_NUMBER}/${TRAVIS_JOB_NUMBER}"
