timedelta: 60
projects:
    - FM-AD
    - TCGA-SARC
    - TCGA-MESO
    - TCGA-THCA
    - TCGA-LGG
    - TARGET-AML
    - TARGET-CCSK
    - TCGA-READ
    - TARGET-NBL
    - TCGA-ACC
    - TCGA-OV
    - TCGA-GBM
    - TCGA-KIRC
    - TCGA-CHOL
    - TCGA-SKCM
    - TCGA-THYM
    - TCGA-DLBC
    - TCGA-TGCT
    - TCGA-UVM
    - TCGA-KICH
    - TCGA-LUSC
    - TCGA-LAML
    - TCGA-PRAD
    - TCGA-STAD
    - TCGA-UCEC
    - TCGA-LIHC
    - TARGET-OS
    - TARGET-RT
    - TCGA-HNSC
    - TCGA-COAD
    - TCGA-ESCA
    - TCGA-BLCA
    - TCGA-KIRP
    - TCGA-UCS
    - TCGA-CESC
    - TCGA-PAAD
    - TCGA-LUAD
    - TCGA-PCPG
    - TARGET-WT
    - TCGA-BRCA
