timedelta: 10
active_projects:
    - FM-AD
    - TCGA-SARC
    - TCGA-MESO
    - TCGA-THCA
    - TCGA-LGG
    - TARGET-AML
    - TARGET-CCSK
    - TCGA-READ
    - TARGET-NBL
    - TCGA-ACC
    - TCGA-OV
    - TCGA-GBM
    - TCGA-KIRC
    - TCGA-CHOL
    - TCGA-SKCM
    - TCGA-THYM
    - TCGA-DLBC
    - TCGA-TGCT
    - TCGA-UVM
    - TCGA-KICH
    - TCGA-LUSC
    - TCGA-LAML
    - TCGA-PRAD
    - TCGA-STAD
    - TCGA-UCEC
    - TCGA-LIHC
    - TARGET-OS
    - TARGET-RT
    - TCGA-HNSC
    - TCGA-COAD
    - TCGA-ESCA
    - TCGA-BLCA
    - TCGA-KIRP
    - TCGA-UCS
    - TCGA-CESC
    - TCGA-PAAD
    - TCGA-LUAD
    - TCGA-PCPG
    - TARGET-WT
    - TCGA-BRCA
legacy_projects:
    - CCLE-MM
    - TCGA-SARC
    - TCGA-READ
    - TARGET-NBL
    - TARGET-CCSK
    - TCGA-LGG
    - CCLE-CESC
    - CCLE-ACC
    - TCGA-ACC
    - CCLE-LAML
    - CCLE-LCLL
    - TARGET-AML
    - TCGA-THCA
    - CCLE-DLBC
    - CCLE-LIHC
    - TCGA-MESO
    - CCLE-THYM
    - CCLE-GBM
    - TCGA-KIRC
    - TCGA-CHOL
    - CCLE-LUSC
    - TCGA-OV
    - CCLE-PRAD
    - TCGA-SKCM
    - CCLE-KIRP
    - TCGA-GBM
    - TCGA-BRCA
    - CCLE-HNSC
    - CCLE-MESO
    - CCLE-THCA
    - CCLE-CHOL
    - CCLE-READ
    - TCGA-LUSC
    - TCGA-THYM
    - TCGA-DLBC
    - TCGA-UCEC
    - TCGA-TGCT
    - CCLE-COAD
    - CCLE-STAD
    - TCGA-LAML
    - TCGA-STAD
    - CCLE-PCPG
    - TCGA-MISC
    - TCGA-CNTL
    - TCGA-FPPP
    - TARGET-AML-IF
    - TARGET-MDLS
    - TARGET-ALL-P2
    - TCGA-PRAD
    - TCGA-UVM
    - CCLE-CNTL
    - TCGA-KICH
    - CCLE-BLCA
    - CCLE-LUAD
    - CCLE-PAAD
    - CCLE-ESCA
    - TCGA-HNSC
    - TARGET-RT
    - TCGA-COAD
    - TCGA-ESCA
    - TCGA-LIHC
    - CCLE-MISC
    - CCLE-LCML
    - TARGET-OS
    - CCLE-OV
    - CCLE-BRCA
    - CCLE-UVM
    - CCLE-SARC
    - CCLE-UCEC
    - CCLE-UCS
    - TCGA-CESC
    - TCGA-PCPG
    - TCGA-LUAD
    - TCGA-KIRP
    - CCLE-LGG
    - TCGA-BLCA
    - CCLE-KIRC
    - TCGA-PAAD
    - TCGA-UCS
    - CCLE-KICH
    - TARGET-WT
    - TARGET-ALL-P1
    - CCLE-SKCM
    - CCLE-TGCT
    - CCLE-FPPP
