[tox]
envlist = py36

[testenv]
changedir = tests
passenv = *
setenv =
  PG_PASS=test
  PG_NAME=automated_test
  ES_PORT=9200
  ES_USE_SSL=False
  ES_VERIFY_CERTS=False
  CA_CERT_PATH=''
  USE_RUNNING_ES=true
usedevelop = true
deps =
    -rrequirements.txt
    -rdev-requirements.txt
install_command = python -m pip install --no-deps {opts} {packages}
commands =
  pip freeze
  pytest -lvv --cov=esbuild --cov-report=html {posargs: -lvrf unit integration}
