[tox]
envlist = py{35,36}

[testenv]
setenv =
  PG_HOST=localhost
  PG_USER=test
  PG_PASS=test
  PG_NAME=automated_test
  ES_HOST='localhost'
  ES_VERSION=5.6.14
  NODE_VERSION=10
  BOTO_CONFIG=/dev/null
deps =
  -rrequirements.txt
  -rdev-requirements.txt
use_develop=true
commands =
  pip freeze
  pytest -lvv --cov esbuild --cov-report term --cov-append tests {posargs}
  coverage html
