[tox]
envlist = py313

[testenv]
passenv = *
setenv =
  NO_PROXY=localhost,postgres,elasticsearch,127.0.0.1,::1,indexd
  no_proxy=localhost,postgres,elasticsearch,127.0.0.1,::1,indexd
  DD_TRACE_ENABLED=False
  PG_ESBUILD_USER=postgres
  PG_USER=test
  PG_PASS=test
  PG_NAME=automated_test
  RO_PG_USER=ro_test
  RO_PG_PASS=ro_test
  ES_USE_SSL=False
  ES_VERIFY_CERTS=False
  INDEXD_USER=admin
  INDEXD_PASS=admin
usedevelop = true
deps =
  -c requirements.txt
  .[dev]
install_command = python -m pip install {opts} {packages}
commands =
  pip freeze
  pytest {posargs: -vv --cov=esbuild --cov-report=html --cov-report=xml:coverage.xml --junitxml=report.xml}

[testenv:publish]
changedir =
passenv =
  TWINE_*
skip_install=true
deps =
    setuptools_scm
    build
    twine
install_command =
    python -m pip install {opts} {packages}
commands =
    python -m setuptools_scm
    python -m build
    python -m twine check dist/*
    python -m twine upload dist/*
commands_post=
