from base import BaseParser


class EsbuildPrivateArgs(BaseParser):
    """
    Esbuild arguments that are forbidden to provide by the master controller user
    """

    @property
    def group(self):
        return dict(
            title='Esbuild private arguments',
            description='Esbuild worker settings generated by master.py',
        )

    @property
    def arguments(self):
        return {
            'index-name': dict(
                help='Index name to upsert projects to.',
            ),
            'awg-mode': dict(
                help='If set, will build in AWG mode. '
                'Will pick up only projects flagged as awg_review = true and '
                'nodes that are part of these projects and are in any of allowed states',
                action='store_true',
            )
        }


class EsbuildUserArgs(BaseParser):
    """
    Esbuild arguments that are provided by the master controller user
    """

    @property
    def group(self):
        return dict(
            title='Esbuild user arguments',
            description='Esbuild worker settings provided by user',
        )

    @property
    def arguments(self):
        return {
            'index-type': dict(
                help='Type of index to build',
                choices=['active', 'legacy', 'awg', 'test'],
                required=True,
            ),
            'build-projects': dict(
                help='If set, builds only set of projects specified (space-separated)',
                nargs='*',
            ),
            'delete': dict(
                help='If passed, delete the nodes in the json file passed with --json_delete',
                action="store_true",
            ),
            'skip-es': dict(
                help='If passed, skip any actual action on es, just build json',
                action="store_true",
            ),
            'json-delete': dict(
                help='File to use to delete nodes',
            ),
            'test-delete': dict(
                help='Test the deletion (skip load & build of index)',
                action='store_true',
            ),
            'selective-caching': dict(
                help='If set, only caches nodes for projects needed. '
                'WARNING: Will skip nodes that do not have project_id',
                action='store_true',
            ),
        }
