from base import BaseArgs


class EsbuildPrivateArgs(BaseArgs):
    """
    Esbuild arguments that are forbidden to provide by the master controller user
    """
    args = {
        'index_name',
        'build_awg',
    }

    def add_args(self, parser):
        private_args = parser.add_argument_group(
            title='Esbuild private arguments',
            description='Esbuild worker settings generated by master.py',
        )

        private_args.add_argument(
            '--index-name', help='Index name to upsert projects to.',
        )
        parser.add_argument(
            '--build-awg', action='store_true',
            help='If set, will build in AWG mode. '
            'Will pick up only projects flagged as awg_review = true and '
            'nodes that are part of these projects and are in any of allowed states',
            default=False
        )
        return parser


class EsbuildUserArgs(BaseArgs):
    """
    Esbuild arguments that are provided by the master controller user
    """
    args = {
        'projects',
        'no_roll',
        'no_cleanup',
        'delete',
        'skip_es',
        'json_delete',
        'test_delete',
        'selective_caching',
    }

    def add_args(self, parser):
        """
        Add esbuild arguments to parser
        """
        esbuild_args = parser.add_argument_group(
            title='Esbuild user arguments',
            description='Esbuild worker settings provided by user',
        )

        esbuild_args.add_argument(
            '--projects', nargs='*',
            help='If set, builds only set of projects specified (space-separated)',
        )
        esbuild_args.add_argument(
            '--no-roll', action="store_true",
            help='If passed, do not roll the alias and delete old indices',
        )
        esbuild_args.add_argument(
            '--no-cleanup', action="store_true",
            help='If passed, do not delete old indices',
        )
        esbuild_args.add_argument(
            '--delete', action="store_true",
            help='If passed, delete the nodes in the json file passed with --json_delete',
        )
        esbuild_args.add_argument(
            '--skip_es', action="store_true",
            help='If passed, skip any actual action on es, just build json',
        )
        esbuild_args.add_argument(
            '--json_delete',
            help='File to use to delete nodes',
        )
        esbuild_args.add_argument(
            '--test_delete', action='store_true',
            help='Test the deletion (skip load & build of index)',
        )
        esbuild_args.add_argument(
            '--selective-caching', action='store_true',
            help='If set, only caches nodes for projects needed. '
            'WARNING: Will skip nodes that do not have project_id',
            default=False,
        )

        return parser
