---
timedelta: 60
active_projects:
  - BEATAML1.0-COHORT
  - BEATAML1.0-CRENOLANIB
  - CGCI-BLGSP
  - CGCI-HTMCP-CC
  - CMI-ASC
  - CMI-MBC
  - CMI-MPC
  - CPTAC-2
  - CPTAC-3
  - CTSP-DLBCL1
  - FM-AD
  - GENIE-DFCI
  - GENIE-GRCC
  - GENIE-JHU
  - GENIE-MDA
  - GENIE-MSK
  - GENIE-NKI
  - GENIE-UHN
  - GENIE-VICC
  - HCMI-CMDC
  - MMRF-COMMPASS
  - NCICCR-DLBCL
  - OHSU-CNL
  - ORGANOID-PANCREATIC
  - REBC-THYR
  - TARGET-ALL-P1
  - TARGET-ALL-P2
  - TARGET-ALL-P3
  - TARGET-AML
  - TARGET-CCSK
  - TARGET-NBL
  - TARGET-OS
  - TARGET-RT
  - TARGET-WT
  - TCGA-ACC
  - TCGA-BLCA
  - TCGA-BRCA
  - TCGA-CESC
  - TCGA-CHOL
  - TCGA-COAD
  - TCGA-DLBC
  - TCGA-ESCA
  - TCGA-GBM
  - TCGA-HNSC
  - TCGA-KICH
  - TCGA-KIRC
  - TCGA-KIRP
  - TCGA-LAML
  - TCGA-LGG
  - TCGA-LIHC
  - TCGA-LUAD
  - TCGA-LUSC
  - TCGA-MESO
  - TCGA-OV
  - TCGA-PAAD
  - TCGA-PCPG
  - TCGA-PRAD
  - TCGA-READ
  - TCGA-SARC
  - TCGA-SKCM
  - TCGA-STAD
  - TCGA-TGCT
  - TCGA-THCA
  - TCGA-THYM
  - TCGA-UCEC
  - TCGA-UCS
  - TCGA-UVM
  - TRIO-CRU
  - VAREPOP-APOLLO
  - WCDT-MCRPC
legacy_projects:
  - CCLE-MM
  - TCGA-SARC
  - TCGA-READ
  - TARGET-NBL
  - TARGET-CCSK
  - TCGA-LGG
  - CCLE-CESC
  - CCLE-ACC
  - TCGA-ACC
  - CCLE-LAML
  - CCLE-LCLL
  - TARGET-AML
  - TCGA-THCA
  - CCLE-DLBC
  - CCLE-LIHC
  - TCGA-MESO
  - CCLE-THYM
  - CCLE-GBM
  - TCGA-KIRC
  - TCGA-CHOL
  - CCLE-LUSC
  - TCGA-OV
  - CCLE-PRAD
  - TCGA-SKCM
  - CCLE-KIRP
  - TCGA-GBM
  - TCGA-BRCA
  - CCLE-HNSC
  - CCLE-MESO
  - CCLE-THCA
  - CCLE-CHOL
  - CCLE-READ
  - TCGA-LUSC
  - TCGA-THYM
  - TCGA-DLBC
  - TCGA-UCEC
  - TCGA-TGCT
  - CCLE-COAD
  - CCLE-STAD
  - TCGA-LAML
  - TCGA-STAD
  - CCLE-PCPG
  - TCGA-MISC
  - TCGA-CNTL
  - TCGA-FPPP
  - TARGET-AML-IF
  - TARGET-MDLS
  - TARGET-ALL-P2
  - TCGA-PRAD
  - TCGA-UVM
  - CCLE-CNTL
  - TCGA-KICH
  - CCLE-BLCA
  - CCLE-LUAD
  - CCLE-PAAD
  - CCLE-ESCA
  - TCGA-HNSC
  - TARGET-RT
  - TCGA-COAD
  - TCGA-ESCA
  - TCGA-LIHC
  - CCLE-MISC
  - CCLE-LCML
  - TARGET-OS
  - CCLE-OV
  - CCLE-BRCA
  - CCLE-UVM
  - CCLE-SARC
  - CCLE-UCEC
  - CCLE-UCS
  - TCGA-CESC
  - TCGA-PCPG
  - TCGA-LUAD
  - TCGA-KIRP
  - CCLE-LGG
  - TCGA-BLCA
  - CCLE-KIRC
  - TCGA-PAAD
  - TCGA-UCS
  - CCLE-KICH
  - TARGET-WT
  - TARGET-ALL-P1
  - CCLE-SKCM
  - CCLE-TGCT
  - CCLE-FPPP
